import 'package:flutter/material.dart';
import 'package:trading_app/screens/home_screen.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Trading App',
      theme: ThemeData.dark(),
      home: const HomeScreen(),
    );
  }
}
dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  fl_chart: ^0.64.0
  http: ^0.13.4